### ISSUE TITLE
STM32F411CE HID platformIO/ArduinoIDE

### ISSUE THREAD

**Issue by flatpedals** [WeActTC/WeAct_HID_Bootloader_F4x1#1]
I'm a student with not much knowledge outside basic C++ and some Arduino/Blue Pill hacking. 
I have a **WeAct v1.3 STM32F411CE** and I'm having a hard time using the **HID Bootloader** outside the provided flashing app ('**WeAct_HID_Flash_NETFramework4+ V10 FluentWPF 191220 AnyCPU**'). In the mentioned app the bootloader is identified with **VID:PID [0483:572A]** but anywhere else I can't connect to it. Tried Arduino IDE and PlatformIO using **Black pill F401CC** board definition. Maybe that definition is the problem. If so, let me know and I'll try to edit it.

The bootloader was successfully flashed using **STM32CubeProgrammer** and seems to be working as intended. **KEY button** gets into bootloader mode and my Windows 10 identifies it as WeAct STM32 HID Bootloader in Devices and Printers.

WeAct HID Flash app can connect to the bootloader: 
`> Soft Version: 1.0.0.0
> Windows Version: 6.2.9200.0
> MCU Enter The Bootloader Method
> Hold down the KEY to Repower or Reboot
> Language: en-US
> Searching for HID Device [0483:572A] ...
> **
> HID device [0483:572A] is found !
> Sending <read FW version> Command ...
> FW version: V1.0 0x431 ROM: 512KB
> Finish`

If I try uploading in PlatformIO or ArduinoIDE, I get the following error message: 
`> Trying to open the comport...
> unable to open comport
> Searching for 1209:BEBA HID device...
##########
> Unable to open the HID device.
*** [upload] Error 1`

platformio.ini looks like this:
`[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = hid
upload_port = anything`

I can't target a specific COM[port] since the HID Bootloader doesn't seem to have one. I also tried installing **Virtual Com Port drivers for STM32 (STSW-STM32102)** but that didn't change anything. Now they are unistalled.

Something is obviously broken since it seems to be looking for a different VID/PID than my board's.

Also, under _Devices and Printers -> WeAct STM32 HID Bootloader -> Properties -> USB Input Device -> Events_ there is a last event that says: **Device not migrated** with the Information:
`Device USB\VID_0483&PID_572A\377834843038 was not migrated due to partial or ambiguous match.
Last Device Instance Id: USB\VID_045E&PID_0800&MI_00\7&129f0203&0&0000
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Location Path: 
Migration Rank: 0xF000FFFFE000F130
Present: false
Status: 0xC0000719
`

I also tried connecting the board to a few other PCs running Win 10 and 7 but same behaviour.
At this point I'm pretty sure I'm doing some very basic thing wrong (like that board definition) or some Windows driver is acting up.

Any help is greatly appreciated, thank you.

**Comment by WeActStudio** [comment]
WeAct_HID_Bootloader_F4x1 is not support  platformIO/ArduinoIDE 
You can try this ：https://github.com/WeActTC/STM32_HID_Bootloader/releases

**Comment by flatpedals** [comment]
Thank you, I flashed the provided bootloader and it is working with platformIO but only for the first flash.
After that, it seems the MCU is never reset and it just hangs, the uploaded sketch doesn't run and the NRST button doesn't get it back into HID bootloader. Pressing the NRST just blinks the user led.  
To get it functional again, I had to reflash WeAct_HID_Bootloader_F4x1. Then after flashing stm32_HID again and then uploading a sketch it just hangs again. 
What am I missing?

**Comment by WeActStudio** [comment]
Use stm32CubeProgmmer to burn stm32-hid -bootloader, do not use WeAct_HID_Bootloader_F4x1 to burn stm32-hid -bootloader, their burn address is different.
Stm32-hid -bootloader firmware running address - 0x8000000, APP jump address -0x8004000, WeAct_HID_Bootloader_F4x1 is the same
